### ISSUE TITLE
Error: "shs.client: error when expecting server to accept challenge (phase 1). possibly the server is busy, does not speak shs or uses a different application cap"

### ISSUE THREAD

**Issue by austinfrey** [ssbc/ssb-tunnel#10]
Browser code example is reporting this error when trying to establish a connection to the target, but server to server tunneling works fine, just having issues with websocket/browser to server tunneling.

```
Error: "shs.client: error when expecting server to accept challenge (phase 1). 
possibly the server is busy, does not speak shs or uses a different application cap"
```
The portal connection seems to be working fine though, just not tunneling to the target. With `config.tunnel.logging` turned on, I get the following output on the pub when `tunnel.connect` gets called from the browser.
```
tunnel:portal - received tunnel request for target:@<target public key>=.ed25519, from:@CyJtmMEk9+vdm8NUQsky9ZuTU5axRaRKH+qP3X2puRM=.ed25519
```

-----
pub/portal details
```
node: 10.14
ssb-server: 15.1.1
ssb-tunnel: 2.0.0
```

target details
```
node: 10.15.1
ssb-server: 14.2.1
```
target config.connections
```
  "connections": {
    "incoming": {
       "net": [
         { "scope": "private", "transform": "shs", "port": 8008, "host": "localhost" }
       ],
       "tunnel": [{
         "scope": "public",
         "transform": "shs",
         "portal": "@<pub/portal public key=.ed25519"
       }]
    }
  }
```

**Comment by dominictarr** [comment]
The server needs to have `"incoming": {"ws": ...}` because the browser cannot connect to net addresses. If it tried to connect to a net server using ws the server would reject the connection and you'd get the error you have described.

**Comment by austinfrey** [comment]
ahh good to know. thanks!
